import AppKit

@MainActor
public final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    /// Set by PasteService right after it writes to the pasteboard so we don't
    /// recapture our own paste.
    public var expectedChangeCount: Int = -1

    private let store: Store
    private let settings: Settings

    private static let skipMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    private static let maxImageBytes = 20 * 1024 * 1024

    public init(store: Store, settings: Settings) {
        self.store = store
        self.settings = settings
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    public func start() {
        stop()
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard pb.changeCount != expectedChangeCount else { return }
        guard !settings.isPaused else { return }

        let types = pb.types ?? []
        if types.contains(where: { Self.skipMarkers.contains($0.rawValue) }) { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bid = front?.bundleIdentifier, settings.excludedBundleIDs.contains(bid) { return }

        guard let item = buildItem(from: pb, sourceApp: front) else { return }
        store.insert(item)
    }

    private func buildItem(from pb: NSPasteboard, sourceApp: NSRunningApplication?) -> ClipItem? {
        let bundleID = sourceApp?.bundleIdentifier
        let appName = sourceApp?.localizedName

        // 1. File URLs
        if let urls = pb.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            return ClipItem(
                kind: .file, text: paths,
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: ContentHasher.hash("file:" + paths)
            )
        }

        // 2. Images
        if let imageData = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            guard imageData.count <= Self.maxImageBytes,
                  let image = NSImage(data: imageData),
                  let png = pngData(from: image)
            else { return nil }
            let filename = UUID().uuidString + ".png"
            do {
                try png.write(to: store.contentURL(filename))
            } catch {
                return nil
            }
            // Card thumbnails render at 240x214pt (up to 2x on Retina); a small
            // pre-scaled copy avoids decoding the full-resolution image on
            // every scroll/redraw of the card row.
            var thumbFilename: String?
            if let thumbPNG = thumbnailData(from: image, maxDimension: 480) {
                let name = UUID().uuidString + "-thumb.png"
                if (try? thumbPNG.write(to: store.contentURL(name))) != nil {
                    thumbFilename = name
                }
            }
            return ClipItem(
                kind: .image, imageFile: filename, thumbFile: thumbFilename,
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: ContentHasher.hash(png)
            )
        }

        // 3. Text (rich or plain)
        guard let raw = pb.string(forType: .string),
              !raw.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        // Hash the plain text so re-copying the same content dedups even when
        // the rich representation differs.
        let hash = ContentHasher.hash("text:" + raw)

        if let rtfData = pb.data(forType: .rtf) {
            let filename = UUID().uuidString + ".rtf"
            try? rtfData.write(to: store.contentURL(filename))
            return ClipItem(
                kind: .richText, text: raw, rtfFile: filename,
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: hash
            )
        }

        return ClipItem(
            kind: isLinkString(raw) ? .link : .text, text: raw,
            sourceAppBundleID: bundleID, sourceAppName: appName,
            contentHash: hash
        )
    }

    private func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff)
        else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func thumbnailData(from image: NSImage, maxDimension: CGFloat) -> Data? {
        let size = image.size
        guard size.width > 0, size.height > 0 else { return nil }
        let scale = min(1, maxDimension / max(size.width, size.height))
        let targetSize = NSSize(width: max(1, size.width * scale), height: max(1, size.height * scale))

        let thumb = NSImage(size: targetSize)
        thumb.lockFocus()
        image.draw(in: NSRect(origin: .zero, size: targetSize),
                   from: NSRect(origin: .zero, size: size),
                   operation: .copy, fraction: 1)
        thumb.unlockFocus()

        return pngData(from: thumb)
    }
}
