import AppKit
#if canImport(ClapCore)
import ClapCore
#endif

@MainActor
public final class ClipboardMonitor: ClipboardSource {
    private var timer: Timer?
    private var lastChangeCount: Int
    /// Set by PasteService right after it writes to the pasteboard so we don't
    /// recapture our own paste.
    public var expectedChangeCount: Int = -1
    public var onCapture: ((ClipItem) -> Void)?

    private let store: Store
    private let settings: Settings

    private static let skipMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public init(store: Store, settings: Settings) {
        self.store = store
        self.settings = settings
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    public func start() {
        stop()
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard pb.changeCount != expectedChangeCount else { return }
        guard !settings.isPaused else { return }

        let types = pb.types ?? []
        if types.contains(where: { Self.skipMarkers.contains($0.rawValue) }) { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bid = front?.bundleIdentifier, settings.excludedBundleIDs.contains(bid) { return }

        guard let item = buildItem(from: pb, sourceApp: front) else { return }
        onCapture?(item)
    }

    private func buildItem(from pb: NSPasteboard, sourceApp: NSRunningApplication?) -> ClipItem? {
        let bundleID = sourceApp?.bundleIdentifier
        let appName = sourceApp?.localizedName

        // 1. File URLs
        if let urls = pb.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            if urls.count == 1,
               let item = ImageProcessor.makeItem(fromImageFile: urls[0], store: store,
                                                  bundleID: bundleID, appName: appName) {
                return item
            }
            let paths = urls.map(\.path).joined(separator: "\n")
            return ClipItem(
                kind: .file, text: paths,
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: ContentHasher.hash("file:" + paths)
            )
        }

        // 2. Images
        if let imageData = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            return ImageProcessor.makeItem(fromPasteboardData: imageData, store: store,
                                           bundleID: bundleID, appName: appName)
        }

        // 3. Text (rich or plain)
        guard let raw = pb.string(forType: .string),
              !raw.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        // Hash the plain text so re-copying the same content dedups even when
        // the rich representation differs.
        let hash = ContentHasher.hash("text:" + raw)

        // A copied color string becomes a swatch card; its formatting (some
        // editors attach RTF) isn't worth keeping.
        if parseColorString(raw) != nil {
            return ClipItem(
                kind: .color, text: raw,
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: hash
            )
        }

        if let rtfData = pb.data(forType: .rtf) {
            let filename = UUID().uuidString + ".rtf"
            try? rtfData.write(to: store.contentURL(filename))
            return ClipItem(
                kind: .richText, text: raw, rtfFile: filename,
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: hash
            )
        }

        return ClipItem(
            kind: isLinkString(raw) ? .link : .text, text: raw,
            sourceAppBundleID: bundleID, sourceAppName: appName,
            contentHash: hash
        )
    }

}
