import AppKit
import UniformTypeIdentifiers

/// Read-only view of a pasteboard. NSPasteboard conforms below; tests use an
/// in-memory fake so the capture logic can be exercised without touching the
/// real (global, mutable) system pasteboard.
public protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    var typeIdentifiers: [String] { get }
    func data(forType type: NSPasteboard.PasteboardType) -> Data?
    func string(forType type: NSPasteboard.PasteboardType) -> String?
    func fileURLs() -> [URL]
}

extension NSPasteboard: PasteboardReading {
    public var typeIdentifiers: [String] { types?.map(\.rawValue) ?? [] }

    public func fileURLs() -> [URL] {
        (readObjects(forClasses: [NSURL.self],
                     options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
    }
}

@MainActor
public final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    /// Set by PasteService right after it writes to the pasteboard so we don't
    /// recapture our own paste.
    public var expectedChangeCount: Int = -1

    private let store: Store
    private let settings: Settings

    private static let skipMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public init(store: Store, settings: Settings,
                initialChangeCount: Int = NSPasteboard.general.changeCount) {
        self.store = store
        self.settings = settings
        self.lastChangeCount = initialChangeCount
    }

    public func start() {
        stop()
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    func check() {
        check(pasteboard: NSPasteboard.general)
    }

    func check(pasteboard pb: PasteboardReading) {
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard pb.changeCount != expectedChangeCount else { return }
        guard !settings.isPaused else { return }

        if pb.typeIdentifiers.contains(where: { Self.skipMarkers.contains($0) }) { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bid = front?.bundleIdentifier, settings.excludedBundleIDs.contains(bid) { return }

        capture(from: pb, bundleID: front?.bundleIdentifier, appName: front?.localizedName)
    }

    private func capture(from pb: PasteboardReading, bundleID: String?, appName: String?) {
        // 1. File URLs
        let urls = pb.fileURLs()
        if !urls.isEmpty {
            captureFiles(urls, bundleID: bundleID, appName: appName)
            return
        }

        // 2. Images — decoded and re-encoded off the main thread; a 20 MB
        // screenshot takes seconds and used to freeze the whole app.
        if let imageData = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            insertImageAsync(data: imageData, fallback: nil,
                             bundleID: bundleID, appName: appName)
            return
        }

        // 3. Text (rich or plain)
        guard let raw = pb.string(forType: .string),
              !raw.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        // Hash the plain text so re-copying the same content dedups even when
        // the rich representation differs.
        let hash = ContentHasher.hash("text:" + raw)

        // A copied color string becomes a swatch card; its formatting (some
        // editors attach RTF) isn't worth keeping.
        if parseColorString(raw) != nil {
            store.insert(ClipItem(
                kind: .color, text: raw,
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: hash
            ))
            return
        }

        if let rtfData = pb.data(forType: .rtf) {
            let filename = UUID().uuidString + ".rtf"
            let wrote = (try? rtfData.write(to: store.contentURL(filename),
                                            options: .atomic)) != nil
            store.insert(ClipItem(
                kind: .richText, text: raw,
                rtfFile: wrote ? filename : nil,  // degrade to plain text if the write failed
                sourceAppBundleID: bundleID, sourceAppName: appName,
                contentHash: hash
            ))
            return
        }

        store.insert(ClipItem(
            kind: isLinkString(raw) ? .link : .text, text: raw,
            sourceAppBundleID: bundleID, sourceAppName: appName,
            contentHash: hash
        ))
    }

    private func captureFiles(_ urls: [URL], bundleID: String?, appName: String?) {
        let paths = urls.map(\.path)
        let joined = paths.joined(separator: "\n")
        let fileItem = ClipItem(
            kind: .file, text: joined, files: paths,
            byteSize: Self.totalFileSize(of: paths),
            sourceAppBundleID: bundleID, sourceAppName: appName,
            contentHash: ContentHasher.hash("file:" + joined)
        )
        // A single copied image file becomes an image card; if decoding fails
        // off-main, the plain file card is inserted instead.
        if urls.count == 1, Self.isImageFile(urls[0]) {
            insertImageAsync(fileURL: urls[0], fallback: fileItem,
                             bundleID: bundleID, appName: appName)
            return
        }
        store.insert(fileItem)
    }

    /// Runs image decode/encode + content-file writes on a background task,
    /// then inserts on the main actor. Inserts `fallback` (if any) when the
    /// bytes turn out not to be a usable image.
    private func insertImageAsync(data: Data? = nil, fileURL: URL? = nil,
                                  fallback: ClipItem?,
                                  bundleID: String?, appName: String?) {
        let store = self.store
        let contentDir = store.contentDir
        Task.detached(priority: .utility) {
            let bytes = data ?? fileURL.flatMap { try? Data(contentsOf: $0) }
            let item = bytes.flatMap {
                ImageProcessor.makeItem(fromData: $0, contentDir: contentDir,
                                        bundleID: bundleID, appName: appName)
            } ?? fallback
            guard let item else { return }
            await MainActor.run { store.insert(item) }
        }
    }

    private static func isImageFile(_ url: URL) -> Bool {
        guard let type = try? url.resourceValues(forKeys: [.contentTypeKey]).contentType
        else { return false }
        return type.conforms(to: .image)
    }

    private static func totalFileSize(of paths: [String]) -> Int64? {
        var total: Int64 = 0
        let fm = FileManager.default
        for path in paths {
            let attrs = try? fm.attributesOfItem(atPath: path)
            if let size = attrs?[.size] as? Int64 { total += size }
        }
        return total > 0 ? total : nil
    }
}
